### ISSUE TITLE
Utility Connect suggests incorrect utility for several zip codes

### ISSUE THREAD

**Issue by jakedouglas** [ArcadiaPower/platform-quickstart#10]
![image](https://user-images.githubusercontent.com/18612/135326815-67a56bb0-26dc-4ee2-a5b4-e3b49f2e9b73.png)

**Comment by KerriDevine** [comment]
I looked into this a little bit more and 08053 is actually served by both ACE and PSE&G: https://power2switch.com/NJ/utility_territory_map/index.html

Future idea: can we maintain an open source mapping of zips to utilities so that we can crowd source fixes when zip code territories change?

**Comment by dlopuch** [comment]
> Future idea: can we maintain an open source mapping of zips to utilities so that we can crowd source fixes when zip code territories change?

Genability does this. We just need to map our utility ID's to genability ID's.
<img width="799" alt="Screen Shot 2021-09-30 at 10 26 09 AM" src="https://user-images.githubusercontent.com/1427329/135502511-7f177269-57f9-4b3d-870e-cc294ed275c2.png">

**Comment by johnnyman727** [comment]
Moving this issue to Jira: https://arcadiapower.atlassian.net/browse/EN-677
