### ISSUE TITLE
Clarify directions around environment variables and new tabs

### ISSUE THREAD

**Issue by collinclarke** [ArcadiaPower/platform-quickstart#13]
Currently, the user might misunderstand where to set environment variables in the various instructions. (.env or directly in bash).
Additionally, the need to open a new tab (leave a process running) is not explicitly stated.

To solve for the env confusion, we should use visual queues in the codeblock or explicit instructions to make it clear that the environment variable is being set directly in the command line.
Similarly for the new tab confusion, we can add explicit instructions to open a new tab or leave that process running

**Comment by johnnyman727** [comment]
Moving into a Jira ticket: https://arcadiapower.atlassian.net/browse/EN-675
