### ISSUE TITLE
Mike's CORRECT creds never got any statements webhooks

### ISSUE THREAD

**Issue by jakedouglas** [ArcadiaPower/platform-quickstart#16]
UC ID `1797`

```
irb(main):025:0> pp uc.utility_accounts.map { |ua| [ua.status, ua.utility_statements.count] }
[[<UtilityAccounts::Status> "active", 1],
 [<UtilityAccounts::Status> "inactive", 0],
 [<UtilityAccounts::Status> "inactive", 0],
 [<UtilityAccounts::Status> "inactive", 1],
 [<UtilityAccounts::Status> "inactive", 1]]
```

There should at least be > 1 statement for the `active` account. Not sure about the `inactive` ones.

![image](https://user-images.githubusercontent.com/18612/135332103-386ded4e-b377-42c8-8dfb-1fc376d9aa67.png)

Despite no statements for some of the `billing_histories` scrapes, they all came back `success: true`, so we need to figure out why he did not get any statements WEBHOOKS.

**Comment by johnnyman727** [comment]
Moving this into two triaged Jira tickets: https://arcadiapower.atlassian.net/browse/UD-2175, https://arcadiapower.atlassian.net/browse/EN-674
