### ISSUE TITLE
Incorrect address on Dominion Account

### ISSUE THREAD

**Issue by clifff** [ArcadiaPower/platform-quickstart#9]
From @christinareimond

> I noticed when using my Dominion account that we’re pulling my old address as service address instead of my current one-- I’m guessing this is a scraper issue. where should I report this? should I go straight to UD?

Not sure where we she is seeing this - should check if we found/created multiple UAs or if only one got pulled. Possible this is a scraper issue and should get forwarded to utility data. May be multiple were found but we accidentally filtered out utility_accounts_discovered

**Comment by jakedouglas** [comment]
In this case:

* 3 UAs were discovered (IDs `6505`, `6506`, `6504`)
* One was marked `active` and pulled 8 statements (`6506`)
* The other two were marked `no_statements`

**Comment by johnnyman727** [comment]
Closing this ticket, triaged by UD: https://github.com/ArcadiaPower/parakeet/pull/4998
